# $FreeBSD: head/bin/sh/tests/Makefile 299094 2016-05-04 23:20:53Z ngie $

.include <bsd.own.mk>

TESTS_SUBDIRS+=	builtins
TESTS_SUBDIRS+=	errors
TESTS_SUBDIRS+=	execution
TESTS_SUBDIRS+=	expansion
TESTS_SUBDIRS+=	parameters
TESTS_SUBDIRS+=	parser
TESTS_SUBDIRS+=	set-e

.include <bsd.test.mk>
